
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  com.networknt.petstore-1.0.1

  Sample SAM Template for com.networknt.petstore-1.0.1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  ParamStage:
    Type: String
    Description: Deployment stage.
    Default: test
  ParamServiceId:
    Type: String
    Description: Unique service id for your application
    Default: com.networknt.petstore-1.0.1

Resources:
  PetstoreFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: petstore-function-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
            - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DirectInvokePetstoreLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action:
                - lambda:InvokeFunction
                - lambda:InvokeAsync
              Effect: Allow
              Resource: "*"

  
  
  PetsGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      
      CodeUri: PetsGetFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided.al2023
      MemorySize: 512
      FunctionName: PetsGetFunction
      Role: !Sub ${PetstoreFunctionRole.Arn}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      
    
  
  PetsPostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      
      CodeUri: PetsPostFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided.al2023
      MemorySize: 512
      FunctionName: PetsPostFunction
      Role: !Sub ${PetstoreFunctionRole.Arn}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      
    
  
  PetsPetIdGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      
      CodeUri: PetsPetIdGetFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided.al2023
      MemorySize: 512
      FunctionName: PetsPetIdGetFunction
      Role: !Sub ${PetstoreFunctionRole.Arn}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      
    
  
  PetsPetIdDeleteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      
      CodeUri: PetsPetIdDeleteFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided.al2023
      MemorySize: 512
      FunctionName: PetsPetIdDeleteFunction
      Role: !Sub ${PetstoreFunctionRole.Arn}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      
    
  


  PetstoreNativeLambdaProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s3://networknt-native-lambda-jar-for-deployment-reference/lambda-native-2.1.34-SNAPSHOT.jar
      Handler: com.networknt.aws.lambda.app.LambdaApp::handleRequest
      Layers:
        - !Ref PetstoreConfigLayer
      Runtime: java11
      MemorySize: 512
      FunctionName: PetstoreNativeLambdaProxyFunction
      Role: !Sub ${PetstoreFunctionRole.Arn}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -Dlight-4j-config-dir=/opt

      Events:
        PetstoreHealthGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: GET
        PetstoreAdmHealthGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /adm/health
            Method: GET
        PetstoreAdmServerInfoGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /adm/server/info
            Method: GET
        PetstoreAdmLoggerGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /adm/logger
            Method: GET
        PetstoreAdmLoggerPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /adm/logger
            Method: POST
        
        PetsGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets
            Method: GET
        
        PetsPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets
            Method: POST
        
        PetsPetIdGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets/{petId}
            Method: GET
        
        PetsPetIdDelete:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets/{petId}
            Method: DELETE
        
  PetstoreConfigLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-app-petstore-config-layer
      Description: Configuration for the petstore
      ContentUri: config/
      CompatibleRuntimes:
        - java11
        - java17
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  
